# Site settings
url: https://apaezs.github.io
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Site information
title: "Alejandro Paez"
description: "Personal Website"
author: "Alejandro Paez"

# Theme settings
theme: minima

# Collections
collections:
  news:
    output: true
  projects:
    output: true

