# Site settings
url: https://apaezs.github.io
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Site information
title: "Alejandro Paez"
description: "Personal Website"
author: "Alejandro Paez"

# Theme
theme: minima

# Minima configuration (disable blog behavior)
minima:
  skin: classic
  show_excerpts: false
  social_links: []


# Collections
collections:
  news:
    output: true
  projects:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: null
show_rss: false
